### ISSUE TITLE
Travis is red in 14.0

### ISSUE THREAD

**Issue by sbejaoui** [OCA/vertical-association#109]

**Comment by pedrobaeza** [comment]
It seems travis definition is not up to date. Maybe @sbidoul can update it.

**Comment by rousseldenis** [comment]
> It seems travis definition is not up to date. Maybe @sbidoul can update it.

It's not travis related.

See this job just re launched on 14.0: https://travis-ci.com/github/OCA/vertical-association/jobs/511982017

I think there is a change in Odoo (but haven't looked furthermore)

**Comment by pedrobaeza** [comment]
I was seeing incorrect builds (with exclamation) not getting to Odoo part:

https://travis-ci.com/github/OCA/vertical-association/jobs/520173116

**Comment by rousseldenis** [comment]
@pedrobaeza I did a fix there for errors in 14.0 #110

**Comment by pedrobaeza** [comment]
Thanks for the patch.
