### ISSUE TITLE
Pre-Migration to version 16.0

### ISSUE THREAD

**Issue by robinkeunen** [OCA/vertical-association#124]
Hi there, 

I'm starting to work on migration to version 16.0. Can someone create a branch ? Or is it too soon ?

Todo
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

Modules to migrate
- [x] membership_extension
- [x] membership_variable_period
- [x] membership_withdrawal

EDIT : I'm posting the PR to avoid double work while we wait for Odoo 16 :
- https://github.com/coopiteasy/vertical-association/pull/3
- https://github.com/coopiteasy/vertical-association/pull/2
- https://github.com/coopiteasy/vertical-association/pull/1

**Comment by pedrobaeza** [comment]
I'm afraid it's too soon, as there are a lot of things in CI linked to branch numbers. You can however do such migrations on your fork, and propose when we populate 16.0 branches.

**Comment by robinkeunen** [comment]
Alright, I'll do that, thanks 👌

**Comment by robinkeunen** [comment]
I'm reopening this issue (w/ a different title) to make my PRs visible and avoid double work. Hope that's ok.

- https://github.com/coopiteasy/vertical-association/pull/3
- https://github.com/coopiteasy/vertical-association/pull/2
- https://github.com/coopiteasy/vertical-association/pull/1
