### ISSUE TITLE
Buying a membership with Initial Fee User Error

### ISSUE THREAD

**Issue by diogocsc** [OCA/vertical-association#129]
<img width="864" alt="image" src="https://user-images.githubusercontent.com/1706650/190711902-fb362d7d-8381-4827-b7f1-587bc27ccfed.png">

Hi there, I've just cloned vertical-association for Odoo 14 and installed membership_initial_fee module.

If I buy a membership without initial fee, everything runs smoothly.
But if I buy one that has initial fee configured I get the error present in the image above.

User errror: 
Cannot create unbalanced journal entry. Ids: [21]
Differences debit - credit: [-50.0]

I believe this might be a configuration issue.
What am I missing ?

**Comment by marcos-mendez** [comment]
Thumbs up same here
