### ISSUE TITLE
membership_extension:Group not applied by default to admin users

### ISSUE THREAD

**Issue by bvanjeelharia** [OCA/vertical-association#141]
## Module
membership_extension

## Describe the bug
This module creates a new menu and applies on the Members App menu. But this group doesn't get applied to admin user(/root user) by default.It should be applied by default atleast to the admin user(and root user).

## To Reproduce
**Affected versions**:
All verisons
1.Install the membership_extension module
2.The Members app menu would not be visible to admin user (unless Manager group for membership module is applied to admin user)

**Expected behavior**
The group should be applied by default to admin(and root user)

**Comment by bvanjeelharia** [comment]
I reverified in the module and found that the group is getting applied to admin user through demo file, so I believe it should be removed from there and added directly

**Comment by xavivars** [comment]
This is still an issue. Should be `no stale` @bvanjeelharia
