### ISSUE TITLE
Membership Delegation Enhancements

### ISSUE THREAD

**Issue by gdgellatly** [OCA/vertical-association#150]
**Is your feature request related to a problem?**
membership_delegate_partner only allows delegation to a single partner as it occurs at the move level

**Describe the solution you'd like**
To be able to delegate partners at the account_move_line level

**Describe alternatives you've considered**
An extension module to the delegate_partner  (say delegate_partner_line) module or to redo delegate_partner to work at the move line level and provide migration script.

**Additional context**
The work itself is quite easy, 3-4 hours, the initial feasibility, design and verification is done, but just wish to know original authors thoughts on best approach. Effort either way is about equal, I just feel that delegate_partner becomes obselete with this extension so may be better to redo that, rather than extension. This is for OCA internal use - currently v14.

\cc @pedrobaeza @OCA/board

**Comment by pedrobaeza** [comment]
I don't understand the motivation for such granularity.

**Comment by gdgellatly** [comment]
IN OCA we bill say Camptiva for multiple memberships, for multiple membership levels for multiple members on an annual basis. Currently we rely on associate members to provide some functionality, but it has limitations.

**Comment by pedrobaeza** [comment]
But all of them delegates in Camptiva AFAIK, so the delegation is down-top, not the other way.

**Comment by gdgellatly** [comment]
No, it doesn't work like that. The invoice goes to the top level partner, we need the individual memberships to the members. Anyway, it is no issue, we can just do as extension. There is some history on this at https://github.com/OCA/vertical-association/pull/122

**Comment by pedrobaeza** [comment]
OK, I don't remember the details, as I'm not using the module anymore. If it makes sense anyway, the granularity can be changed on the module itself.

**Comment by gdgellatly** [comment]
Because of `contract_membership_delegated_partner` for now I am going to go extension module and not break anything, can revisit in future.
