### ISSUE TITLE
V10 Bug in Menu View of membership_extension

### ISSUE THREAD

**Issue by lucode** [OCA/vertical-association#36]
It seem there is a bug in membership_extension module in the configration menu view.
![2017-07-27 13_43_44-vertical-exchange - c__users_lucash_pycharmprojects_koina_odoo_vertical-exchang](https://user-images.githubusercontent.com/2928740/28668762-b87e1d1a-72d1-11e7-8727-6ac37344ad0a.png)
If only a single menu exists and you ad a new meni item, the single item converts into a folder item and you can't access the view that was linked to this item anymore. As far as I now you have to create a new subitem for the missing Membership Type view.

**Comment by pedrobaeza** [comment]
Thanks for the report. Can you please make a PR solving the problem?

**Comment by pedrobaeza** [comment]
@chienandalu is this fixed?

**Comment by chienandalu** [comment]
@pedrobaeza Yes, it's what this @lucode PR fixed: https://github.com/OCA/vertical-association/pull/37/files
