### ISSUE TITLE
[10.0] Computing field values on install of membership_extension is taking enormous amounts of time

### ISSUE THREAD

**Issue by NL66278** [OCA/vertical-association#45]
For a database of ca. 50.000 partners, and with just installed membership (so there are actually no members yet) installing membership_extension can take many hours:
 INFO odownbtst10 odoo.models: Storing computed values of res.partner fields membership_categories, membership_category_ids, membership_last_start

**Comment by pedrobaeza** [comment]
Do you see any possible way to speed up this computation (with `read_group` or similar)?

**Comment by NL66278** [comment]
@pedrobaeza I did not look further into this, as we abandoned use of the module. We had problems with the overlap with contracts, so we wrote our own module for membership based on contracts (will be offered to the oca as part of the crm repository).

**Comment by pedrobaeza** [comment]
OK, we are using it without problems since v8. It's a pity not to have you aboard...

**Comment by pedrobaeza** [comment]
Closing as no PR has been proposed as it's an improvement.
