### ISSUE TITLE
[10.0] Variable period not working

### ISSUE THREAD

**Issue by jayo2005** [OCA/vertical-association#49]
Hi I am using the membership_variable_period module but it is not calculating the dates correctly. I created a product for 1 Month variable. When I select the product when buying membership the end date is wrong as it only puts in the last date of the month the membership was purchased.
![1](https://user-images.githubusercontent.com/7015925/32949820-17390798-cb9c-11e7-97d6-3c34dd9f9f92.jpg)

As you see below the End date is wrong.

![2](https://user-images.githubusercontent.com/7015925/32949846-28e51680-cb9c-11e7-8ec2-63023a62b6fc.jpg)

**Comment by pedrobaeza** [comment]
Do you have membership_prorrate module also installed?

**Comment by jayo2005** [comment]
Yes

**Comment by jayo2005** [comment]
Thanks I removed the membership_prorrate and working as I expected now.
