### ISSUE TITLE
Needs help on membership_variable period

### ISSUE THREAD

**Issue by Cedric-Pigeon** [OCA/vertical-association#91]
I am really interested in his feature but I do not understand the dependency on membership_extension which brings a lot of stuff I do not need.

Could anyone help me?

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza ?

**Comment by Cedric-Pigeon** [comment]
ok sorry I see now

**Comment by pedrobaeza** [comment]
OK, if I don't remember bad, it's because periods are not properly updated. Any way, this module is a must-have for being able to manage properly membership IMO, and it's not so heavy.

**Comment by Cedric-Pigeon** [comment]
@pedrobaeza I agree with you but it is a nightmare to install on a database with thousands of partners. Compute methods run for hours...

**Comment by pedrobaeza** [comment]
Well, I think a bit of work can put of optimizing that installation pre-creating the columns and computing only the partners with membership lines.

**Comment by Cedric-Pigeon** [comment]
yes I am working in this way but this fields turns me crazy:https://github.com/OCA/vertical-association/blob/12.0/membership_extension/models/res_partner.py#L49
